import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import { Player } from "@/components/Player";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black text-slate-900 dark:text-slate-50`}
      >
        <div className="flex h-screen overflow-hidden">
             {/* Sidebar Area */}
            <aside className="hidden md:block w-64 flex-shrink-0 z-20">
               <Sidebar />
            </aside>
            
            {/* Main Content Area */}
            <main className="flex-1 flex flex-col min-w-0 overflow-hidden relative">
              <div className="flex-1 overflow-y-auto pb-24 scroll-smooth">
                 {children}
              </div>
            </main>
            
            {/* Player (Fixed) */}
            <Player />
        </div>
      </body>
    </html>
  );
}
